### PR TITLE
Fix building bin wheels for macOS

### LINKED ISSUE #4: Add OSX Wheels
We should [add back](https://github.com/deshaw/nbstripout-fast/pull/3/commits/9128e178b8227078c44b354024ec89437cc6d689) the OSX wheels after https://github.com/PyO3/maturin/issues/1080#issuecomment-1330000265 is fixed.

### PR DESCRIPTION
**Pull request by messense**
Closes #4

### CODE REVIEW

**Comment by mlucool** [comment]
I seemed to have missed this PR, is this still up to date? If so, can you add a few comments as to why/how this fixes OSX. Both for my understanding and so we don't break it later.

**Comment by messense** [comment]
Yes, mostly this: https://pyo3.rs/v0.19.2/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror

**Comment by mlucool** [comment]
What type of mac did you test on? On my M2 mac, when I run `cargo run -- -t examples/example.ipynb` I get the following error:
```
   Compiling nbstripout-fast v1.0.1 (/path/to/nbstripout-fast)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-Wl,-exported_s
...
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation
```

**Comment by felixgwilliams** [comment]
> On my M2 mac, when I run cargo run -- -t examples/example.ipynb I get the following error:

I tried this on my M2 mac and it works if you insert `--no-default-features` before the `--`. It also works if you add a `build.rs` file as suggested in https://pyo3.rs/main/building_and_distribution#macos.

This project looks really useful, so as a mac user I think it would be great if it could be made available for mac.

**Comment by Carreau** [comment]
I was pinged in other channels to try this, here is what I get on my M1:

```
(|nbstripout) nbstripout-fast[macos-bin-wheels ✗]  $ arch
arm64
(|nbstripout) nbstripout-fast[macos-bin-wheels ✗]  $ cargo run --no-default-features -- -t examples/example.ipynb
warning: type alias `JSONMap` is never used
 --> src/stripoutlib.rs:6:6
  |
6 | type JSONMap = serde_json::Map<String, serde_json::Value>;
  |      ^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: function `pop_recursive` is never used
  --> src/stripoutlib.rs:10:4
   |
10 | fn pop_recursive(d: &mut serde_json::Value, key: &str) {
   |    ^^^^^^^^^^^^^

warning: function `determine_keep_output` is never used
  --> src/stripoutlib.rs:32:4
   |
32 | fn determine_keep_output(cell: &JSONMap, default: bool) -> Result<bool, String> {
   |    ^^^^^^^^^^^^^^^^^^^^^

warning: function `strip_output` is never used
  --> src/stripoutlib.rs:65:8
   |
65 | pub fn strip_output(
   |        ^^^^^^^^^^^^

warning: `nbstripout-fast` (lib) generated 4 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/nbstripout-fast -t examples/example.ipynb`
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "2b8656a0",
   "metadata": {},
   "source": [
    "# Welcome to my notebook"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "490d9d7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "1 + 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d28c8451",
   "metadata": {},
   "outputs": [],
   "source": [
    "x = 2\n",
    "x +1"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c6785fd8",
   "metadata": {},
   "source": [
    "## A section"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "258f8509",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f39b636",
   "metadata": {},
   "outputs": [],
   "source": [
    "x += 3\n",
    "x"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

I also got a warning when building the wheel:

```
⚠️  Warning: You specified maturin >=0.13, <0.14 in pyproject.toml under `build-system.requires`, but the current maturin version is 1.3.
```

But I'm not too familiar with rust, so not sure what to make of it.

I think/guess we can add a
```

 // TODO: add custom errors instead of returning a string
+#[cfg_attr(not(feature = "extension-module"), allow(unused))]
 pub fn strip_output(
     nb: &mut serde_json::Value,
     keep_output: bool,
```

(if I get the syntax right) and maybe a 

```
 [build-system]
-requires = ["maturin>=0.13,<0.14"]
+requires = ["maturin>1.3"]
```

Depending on how strict we want to be WRT warnings.

I've also seen Linker error on CI-Buildwheel when using emulation for Mx chips, but I belive now github have Mx runners:

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Review by peytondmurray — APPROVED** [review]
Thanks @messense for this change! :rocket: It's been a while since I looked at this code and ended up disabling macos wheel builds, but I'm glad this is back.

@mlucool @messense Last time I worked on this, it wasn't possible to distribute both bindings and a binary in one build step. [It looks like there's a straightforward path here, though](https://www.maturin.rs/bindings.html?highlight=bindings#both-binary-and-library), so we may want to do that here. I think all we'd need to do is always build this as an `extension-module` and then add a `[project.scripts]` entry to `pyproject.toml`. 

Anyway, maybe that's out of scope for this change, so I'll approve this for now.

**Comment by mlucool** [comment]
Merging, we'll make a follow-up PR for errors

**Pull request merged**
